const CHUNK_PUBLIC_PATH = "server/app/_not-found/page.js";
const runtime = require("../../chunks/ssr/[turbopack]_runtime.js");
runtime.loadChunk("server/chunks/ssr/81592_next_6b5dc8._.js");
runtime.loadChunk("server/chunks/ssr/[project]__bc1a21._.js");
runtime.loadChunk("server/chunks/ssr/39d15_@clerk_shared_dist_05043e._.js");
runtime.loadChunk("server/chunks/ssr/65579_@clerk_backend_dist_fcd05e._.js");
runtime.loadChunk("server/chunks/ssr/57877_@swc_helpers_cjs__interop_require_default_cjs_51a312._.js");
runtime.loadChunk("server/chunks/ssr/src_30aaa5._.js");
runtime.loadChunk("server/chunks/ssr/08b5e__pnpm_11a6c9._.js");
runtime.getOrInstantiateRuntimeModule("[project]/apps/web/.next-internal/server/app/_not-found/page/actions.js { ACTIONS_MODULE0 => \"[project]/node_modules/.pnpm/@clerk+nextjs@7.8.2_next@14.2.35_react-dom@18.3.1_react@18.3.1/node_modules/@clerk/nextjs/dist/esm/app-router/server-actions.js [app-rsc] (ecmascript, action, ecmascript)\", ACTIONS_MODULE1 => \"[project]/node_modules/.pnpm/@clerk+nextjs@7.8.2_next@14.2.35_react-dom@18.3.1_react@18.3.1/node_modules/@clerk/nextjs/dist/esm/app-router/keyless-actions.js [app-rsc] (ecmascript)\" } [app-rsc] (ecmascript)", CHUNK_PUBLIC_PATH);
module.exports = runtime.getOrInstantiateRuntimeModule("[project]/node_modules/.pnpm/next@14.2.35_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/esm/build/templates/app-page.js?page=/_not-found/page { COMPONENT_0 => \"[project]/apps/web/src/app/layout.tsx [app-rsc] (ecmascript, Next.js server component)\", COMPONENT_1 => \"[project]/node_modules/.pnpm/next@14.2.35_react-dom@18.3.1_react@18.3.1/node_modules/next/dist/client/components/not-found-error.js [app-rsc] (ecmascript, Next.js server component)\", METADATA_2 => \"[project]/apps/web/src/app/icon.svg.mjs { IMAGE => \\\"[project]/apps/web/src/app/icon.svg [app-rsc] (static)\\\" } [app-rsc] (structured image object, ecmascript)\" } [app-rsc] (ecmascript) <facade>", CHUNK_PUBLIC_PATH).exports;
