export enum TripRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER',
  VIEWER = 'VIEWER',
}

export enum TripPrivacy {
  PRIVATE = 'PRIVATE',
  SHARED = 'SHARED',
  PUBLIC = 'PUBLIC',
}

export enum TripStatus {
  PLANNING = 'PLANNING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  ARCHIVED = 'ARCHIVED',
}

export enum InvitationStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  DECLINED = 'DECLINED',
  EXPIRED = 'EXPIRED',
}

export enum ActivityStatus {
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ExpenseCategory {
  ACCOMMODATION = 'ACCOMMODATION',
  TRANSPORT = 'TRANSPORT',
  FOOD = 'FOOD',
  ACTIVITIES = 'ACTIVITIES',
  SHOPPING = 'SHOPPING',
  ENTERTAINMENT = 'ENTERTAINMENT',
  EMERGENCY = 'EMERGENCY',
  OTHER = 'OTHER',
}

export enum SplitType {
  EQUAL = 'EQUAL',
  EXACT = 'EXACT',
  PERCENTAGE = 'PERCENTAGE',
  SHARES = 'SHARES',
}

export enum SettlementStatus {
  PENDING = 'PENDING',
  SETTLED = 'SETTLED',
}

export enum TaskPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
}

export enum NotificationType {
  TRIP_INVITATION = 'TRIP_INVITATION',
  ITINERARY_UPDATED = 'ITINERARY_UPDATED',
  EXPENSE_ADDED = 'EXPENSE_ADDED',
  SETTLEMENT_REMINDER = 'SETTLEMENT_REMINDER',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  EMERGENCY_TRIGGERED = 'EMERGENCY_TRIGGERED',
  TRAILWATCH_ALERT = 'TRAILWATCH_ALERT',
  SYSTEM = 'SYSTEM',
}

export enum TrailWatchSeverity {
  INFO = 'INFO',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum TrailWatchAlertType {
  WEATHER = 'WEATHER',
  ROAD_INCIDENT = 'ROAD_INCIDENT',
  TRAIL_INCIDENT = 'TRAIL_INCIDENT',
  VISIBILITY = 'VISIBILITY',
  HEAVY_RAIN = 'HEAVY_RAIN',
  FLOODING = 'FLOODING',
  LANDSLIDE = 'LANDSLIDE',
  ROAD_CLOSURE = 'ROAD_CLOSURE',
  COMMUNITY_REPORT = 'COMMUNITY_REPORT',
  ROUTE_CHANGE = 'ROUTE_CHANGE',
  ACTIVITY_IMPACT = 'ACTIVITY_IMPACT',
}

export enum TrailReportCategory {
  ROAD_BLOCKED = 'ROAD_BLOCKED',
  HEAVY_TRAFFIC = 'HEAVY_TRAFFIC',
  WATERLOGGING = 'WATERLOGGING',
  LANDSLIDE = 'LANDSLIDE',
  TRAIL_DAMAGED = 'TRAIL_DAMAGED',
  POOR_VISIBILITY = 'POOR_VISIBILITY',
  WEATHER_ISSUE = 'WEATHER_ISSUE',
  UNSAFE_PASSAGE = 'UNSAFE_PASSAGE',
  ROAD_CONSTRUCTION = 'ROAD_CONSTRUCTION',
  OTHER = 'OTHER',
}

export enum VerificationStatus {
  UNVERIFIED = 'UNVERIFIED',
  COMMUNITY_CONFIRMED = 'COMMUNITY_CONFIRMED',
  MODERATOR_VERIFIED = 'MODERATOR_VERIFIED',
  OFFICIAL_SOURCE = 'OFFICIAL_SOURCE',
  EXPIRED = 'EXPIRED',
}

export enum RouteStatus {
  NORMAL = 'NORMAL',
  CAUTION = 'CAUTION',
  DISRUPTED = 'DISRUPTED',
  CLOSED = 'CLOSED',
  UNKNOWN = 'UNKNOWN',
}
